name: Claude Code Development

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  claude:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Project Setup
      run: |
        npm run setup
        npm run dev:daemon
    
    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      
    # Custom instructions for Claude Code when working with this project
     custom_instructions: |
       The project is already set up with all dependencies installed. The server is already running at localhost:3000. 
       Logs from it are being written to logs.txt. If needed, you can query the db with the 'sqlite3' cli. 
       If needed, use the mcp_playwright set of tools to launch a browser and interact with the app.
    
    # MCP Server Configuration
     mcp_config: |
       {
         "mcpServers": {
           "playwright": {
             "command": "npx",
             "args": [
               "@playwright/mcp@latest",
               "--allowed-origins",
               "localhost:3000,cdn.tailwindcss.com,esm.sh"
             ]
           }
         }
       }
    
    # Tool permissions for Claude Code
     allowed_tools: "Bash(npm:*),Bash(sqlite3:*),mcp_playwright_browser_snapshot,mcp_playwright_browser_click"